### PR TITLE
Provenance refactor for speed and functionality

### PR DESCRIPTION
**Pull request by bwalsh**
This PR contains : 
* increase in speed - graph now renders  < 1 sec.
* functionality:
  * hide/show/zoom nodes
  * shift-holdtap now selects entire path of node
  * region select & zoom
* convenience:
  * cytoscape test fixture to enable `yarn start` react development

image

### CODE REVIEW

**Comment by kellrott** [comment]
Subject wise, provenance should probably be moved from the `queries` directory to the `building` directory.

**Comment by bwalsh** [comment]
> Subject wise, provenance should probably be moved from the `queries` directory to the `building` directory.

Done
image

**Comment by kellrott** [comment]
Is there a way to make the graph view smaller? Currently, on my screen it so large, I have to scroll past it to see what was clicked on.

**Comment by bwalsh** [comment]
> Is there a way to make the graph view smaller? Currently, on my screen it so large, I have to scroll past it to see what was clicked on.

done. now configurable.  (defaults to h:500px - was 1000px )

image

**Comment by kellrott** [comment]
:+1:

**Pull request merged**
